{% set name = "ax-platform" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ax-platform-{{ version }}.tar.gz
  sha256: eae847151e47ec6e7f0c4b7add9273d8d4e0d759abec795bdbb938a001fa63da

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=34.4
    - setuptools-scm
  run:
    - python >=3.9
    - botorch ==0.10.0
    - jinja2
    - pandas
    - scipy
    - scikit-learn
    - ipywidgets
    - plotly >=5.12.0
    - typeguard
    - pyre-extensions

test:
  imports:
    - ax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facebook/Ax
  summary: Adaptive Experimentation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpanai
    - thewchan
