{% set python_min = "3.10" %}
{% set name = "ax-platform" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3c9a268acc68a70167c6a003686137ebcb6ec745a444d972d400b2d3f170e2b2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=34.4
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - botorch ==0.14.0
    - jinja2
    - pandas
    - scipy
    - scikit-learn
    - ipywidgets
    - plotly >=5.12.0
    - pyre-extensions
    - sympy
    - markdown

test:
  imports:
    - ax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/facebook/Ax
  summary: Adaptive Experimentation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpanai
    - thewchan
