{% set name = "ax-platform" %}
{% set version = "0.3.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ax-platform-{{ version }}.tar.gz
  sha256: 750d75ffca63bd7bd1257ec16024520122a560dcef7df7432e6346f68de7bced

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=34.4
    - setuptools-scm
  run:
    - botorch ==0.9.4
    - ipywidgets
    - jinja2
    - pandas
    - plotly >=5.12.0
    - pyre-extensions
    - python >=3.9
    - scikit-learn
    - scipy
    - typeguard ==2.13.3

test:
  imports:
    - ax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facebook/Ax
  summary: Adaptive Experimentation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpanai
    - thewchan
