{% set name = "ax-platform" %}
{% set version = "0.3.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ax-platform-{{ version }}.tar.gz
  sha256: 91f6a7d0eb08826e2f3f6a17fa64d4c9e2980ecd2147ed6418d7340c302961c1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=34.4
    - setuptools-scm
  run:
    - botorch ==0.9.5
    - ipywidgets
    - jinja2
    - pandas
    - plotly >=5.12.0
    - pyre-extensions
    - python >=3.9
    - scikit-learn
    - scipy
    - typeguard ==2.13.3

test:
  imports:
    - ax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facebook/Ax
  summary: Adaptive Experimentation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpanai
    - thewchan
