{% set name = "ax-platform" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ax-platform-{{ version }}.tar.gz
  sha256: 48522780e9deeb6f874a14a738dbb78be7c028a15a00e0fc815e022739bafeea

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=34.4
    - setuptools-scm
  run:
    - botorch ==0.8.3
    - ipywidgets
    - jinja2
    - pandas
    - plotly >=5.12.0
    - python >=3.7
    - scikit-learn
    - scipy
    - typeguard ==2.13.3

test:
  imports:
    - ax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facebook/Ax
  summary: Adaptive Experimentation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpanai
    - thewchan
