{% set name = "ax-platform" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ax-platform-{{ version }}.tar.gz
  sha256: ffae1e0108e07fc6511e4ce8214629dcf4048af67fbfb553f8f50a4788c6b44e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - botorch ==0.4.0
    - jinja2
    - pandas
    - plotly
    - python >=3.7
    - scikit-learn
    - scipy
    - typeguard

test:
  imports:
    - ax
    - ax.benchmark
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facebook/Ax
  summary: Adaptive Experimentation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpanai
