schema_version: 1

context:
  name: ax-platform
  version: "1.1.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: e280e8ea2c71027b5e352cb2827a164c0ab4594a58c575dd0d411083c8740a34

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=34.4
    - setuptools-scm
    - wheel
  run:
    - python >=${{ python_min }}
    - botorch >=0.15.1
    - jinja2
    - pandas
    - scipy
    - scikit-learn
    - ipywidgets
    - plotly >=5.12.0
    - pyre-extensions
    - sympy
    - markdown
    # from pytorch[pymoo]
    - pymoo

tests:
  - python:
      imports:
        - ax
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Adaptive Experimentation
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/facebook/Ax

extra:
  recipe-maintainers:
    - rpanai
    - thewchan
