schema_version: 1

context:
  name: ax-platform
  version: "1.2.3"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 2ae26b29a63691a81f0feb8f02e6d2bd436d0d685d25a2c33f910806fc15097b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=34.4
    - setuptools-scm
    - wheel
  run:
    - python >=${{ python_min }}
    - botorch >=0.17.0,<0.17.1dev9999
    - jinja2
    - pandas
    - scipy
    - scikit-learn
    - ipywidgets
    - plotly >=5.12.0
    - pyre-extensions
    - sympy
    - markdown
    - python-graphviz
    # from pytorch[pymoo]
    - pymoo

tests:
  - python:
      imports:
        - ax
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Adaptive Experimentation
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/facebook/Ax

extra:
  recipe-maintainers:
    - rpanai
    - thewchan
